# Generated by Django 5.2.6 on 2025-09-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamePic', models.CharField(max_length=20)),
                ('MainPicture', models.ImageField(upload_to='')),
            ],
        ),
    ]
