# Generated by Django 5.2.6 on 2025-09-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexbackground',
            name='MainPicture',
            field=models.ImageField(upload_to='background/'),
        ),
    ]
